spring.application.name=start_up
server.port=8080
# CONFIGURACION DE credenciales de MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/duoc_start_up
spring.datasource.username=root
spring.datasource.password=
# CONFIGURACION DE SPRING CON MYSQL
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect